<body>

<ul class="maincss">

    <div class="main1">
        <li>
            <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/011-truck.svg'); ?>"/>
            <div class="main2">
                <label class="label1">free delivery</label>
                <label>on orders over 100$</label>
            </div>
        </li>
    </div>

    <div class="main1">
        <li>
            <img class="images" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/003-gift.svg'); ?>" alt="gift" />
            <div class="main2">
                <label class="label1">free gifts</label>
                <label>with every other purchase</label>
            </div>
        </li>
    </div>

    <div class="main1">
        <li>
            <img class="images" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/006-padlock.svg'); ?>" alt="padlock" />
            <div class="main2">
                <label class="label1">fast shipping everywhere!!</label>
            </div>
        </li>
    </div>
</ul>

</body>


