<div class="main3">
<h3>Contacts Details</h3>

    <div class="main4">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/002-phone-receiver.svg'); ?>"/>
        <div>
            <p> +995 123 123</p>
            <p> +995 234 234</p>
        </div>
    </div>

    <div class="main4">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/024-email.svg'); ?>"/>
        <div>
            <p>my@gmail.com</p>
            <p>random@gmail.com</p>
        </div>
    </div>

    <div class="main4">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/003-skype-logo.svg'); ?>"/>
        <div>
            <p>load skype</p>
        </div>
    </div>

</div>


