<div class="payments">
    <div class="payment2">
        <h4>pay me.</h4>
        <p>Call us at +995 345 456 for any assistance required.</p>
    </div>
    <div class="payment-list">
        <img style="padding-right: 20px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/mastercard.png'); ?>"/>
        <img style="padding-right: 20px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/paypal.png'); ?>"/>
        <img style="padding-right: 20px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/american_express.png'); ?>"/>
        <img style="padding-right: 20px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/maestro.png'); ?>"/>
        <img style="padding-right: 20px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/visa.png'); ?>"/>
    </div>
</div>
